FROM        node:24-alpine

EXPOSE      3000

RUN         apt-get update \
            && apt-get install -y libssl-dev procps \
            && apt-get clean

WORKDIR     /app

ENV         TZ=UTC

ENTRYPOINT ["/bin/sh", "-c" , "npx prisma db push && npm run start:dev"]
